micronaut:
    application:
        name: complete
application:
    max: 50
datasources:
    default:
        url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
        username: ${JDBC_USER:sa}
        password: ${JDBC_PASSWORD:""}
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
    default:
        packages-to-scan:
        - 'odelia.micronaut.jpa.kotlin.domain'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true